<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Klik Untuk Aktivasi Email  Log-in</name>
   <tag></tag>
   <elementGuidId>099f7def-aa3b-44b6-9305-f7b2a1f9073c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='message']/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[2]/td/p[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u23291266.ct.sendgrid.net/ls/click?upn=gZdSL1niv8Dq-2F1Zk-2BnPKp4he5BAehP7RPkC9yLunVoFC-2BmgCIKjmbiWezcj7IWNxgFbCMxRMB64jP0Y7MevHp1wYNms3JSKu9WlzH51Zh-2FJR0e98VYXb9f4b17yaHTryCYNabLxQGmJO6h5hwCK3C8yHHEjT6QxBcrDFcnOShJ3Y4EUlI2SoBItn8kMiRuuUSHosCaR9lkjb0kURGqDE6pqRt6wYnW8oiBlHBcyMSb0-3DgEhm_imX02d7rVkttAOa4RN2oHIAakbPun4UaqliPjpu0dj8LClgHDpGYqw7jrC9HR9V35TmVjBlQxlgmGf8t0sRVzK04ei-2FjB8FqD1dIiusLngQ6On6W15S1N6Hivev-2FeevDffkWZCSSsg3claaRtV-2Bjzw6gYBjjXzpzo4QKkJgcKWlkqGQSuUL9LX4DxMoEABry9s-2FE1FpDJ9q9YuMtAnYhcOKAmJkD9uIZAvdzU5Ed18dsVSkqMHV432rOWSR1nL-2Fzh-2Fi9FbTRrx-2FsOW98rLi-2FkOIq6hOEZGEvNJHfGZElbT1oVfK3glJbv0drkBIjkSsqROHd1hX7jXsG2RNsPgGSPvF0M1ftFCTQyO6nSXVkywU-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Klik Untuk Aktivasi Email &amp; Log-in
                                                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;content&quot;]/tbody[1]/tr[2]/td[@class=&quot;outerpadding&quot;]/table[@class=&quot;innerpadding&quot;]/tbody[1]/tr[2]/td[1]/p[6]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='message']/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[2]/td/p[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Klik Untuk Aktivasi Email &amp; Log-in')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ipasha96910@dispostable.com'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username/E-mail :'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='di sini'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Klik Untuk Aktivasi Email &amp; Log-in']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://u23291266.ct.sendgrid.net/ls/click?upn=gZdSL1niv8Dq-2F1Zk-2BnPKp4he5BAehP7RPkC9yLunVoFC-2BmgCIKjmbiWezcj7IWNxgFbCMxRMB64jP0Y7MevHp1wYNms3JSKu9WlzH51Zh-2FJR0e98VYXb9f4b17yaHTryCYNabLxQGmJO6h5hwCK3C8yHHEjT6QxBcrDFcnOShJ3Y4EUlI2SoBItn8kMiRuuUSHosCaR9lkjb0kURGqDE6pqRt6wYnW8oiBlHBcyMSb0-3DgEhm_imX02d7rVkttAOa4RN2oHIAakbPun4UaqliPjpu0dj8LClgHDpGYqw7jrC9HR9V35TmVjBlQxlgmGf8t0sRVzK04ei-2FjB8FqD1dIiusLngQ6On6W15S1N6Hivev-2FeevDffkWZCSSsg3claaRtV-2Bjzw6gYBjjXzpzo4QKkJgcKWlkqGQSuUL9LX4DxMoEABry9s-2FE1FpDJ9q9YuMtAnYhcOKAmJkD9uIZAvdzU5Ed18dsVSkqMHV432rOWSR1nL-2Fzh-2Fi9FbTRrx-2FsOW98rLi-2FkOIq6hOEZGEvNJHfGZElbT1oVfK3glJbv0drkBIjkSsqROHd1hX7jXsG2RNsPgGSPvF0M1ftFCTQyO6nSXVkywU-3D')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
